USE [DOOR]
GO
/****** Object:  Table [dbo].[R_ORDER] ******/
DROP TABLE if EXISTS dbo.R_ORDER

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[R_ORDER](
	[seq][int] IDENTITY(1,1) NOT NULL,
	[EMail] [varchar](50) NOT NULL,
	[Passwd] [varchar](16) NOT NULL,
	[Obverse] [int] NOT NULL,
	[Reverse] [int] NOT NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_R_ORDER] PRIMARY KEY CLUSTERED 
(
	[seq] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
