#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameCard
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NameCard")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 拡張メソッドの定義
    partial void OnCreated();
    partial void InsertM_ACCOUNT(M_ACCOUNT instance);
    partial void UpdateM_ACCOUNT(M_ACCOUNT instance);
    partial void DeleteM_ACCOUNT(M_ACCOUNT instance);
    partial void InsertR_ORDER(R_ORDER instance);
    partial void UpdateR_ORDER(R_ORDER instance);
    partial void DeleteR_ORDER(R_ORDER instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NameCardConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<M_ACCOUNT> M_ACCOUNT
		{
			get
			{
				return this.GetTable<M_ACCOUNT>();
			}
		}
		
		public System.Data.Linq.Table<R_ORDER> R_ORDER
		{
			get
			{
				return this.GetTable<R_ORDER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.M_ACCOUNT")]
	public partial class M_ACCOUNT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _seq;
		
		private string _EMail;
		
		private string _Passwd;
		
		private string _LastName;
		
		private string _FirstName;
		
		private string _Pref;
		
		private string _City;
		
		private string _Address;
		
		private string _Apartment;
		
		private string _Role;
		
		private string _SubRole;
		
		private string _LastNameEn;
		
		private string _FirstNameEn;
		
		private string _PrefEn;
		
		private string _CityEn;
		
		private string _AddressEn;
		
		private string _ApartmentEn;
		
		private string _RoleEn;
		
		private string _SubRoleEn;
		
		private string _Tel;
		
		private string _Fax;
		
		private int _AdminKbn;
		
		private System.Nullable<System.DateTime> _CREATE_DATE;
		
		private System.Nullable<System.DateTime> _UPDATE_DATE;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnseqChanging(int value);
    partial void OnseqChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnPasswdChanging(string value);
    partial void OnPasswdChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnPrefChanging(string value);
    partial void OnPrefChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnApartmentChanging(string value);
    partial void OnApartmentChanged();
    partial void OnRoleChanging(string value);
    partial void OnRoleChanged();
    partial void OnSubRoleChanging(string value);
    partial void OnSubRoleChanged();
    partial void OnLastNameEnChanging(string value);
    partial void OnLastNameEnChanged();
    partial void OnFirstNameEnChanging(string value);
    partial void OnFirstNameEnChanged();
    partial void OnPrefEnChanging(string value);
    partial void OnPrefEnChanged();
    partial void OnCityEnChanging(string value);
    partial void OnCityEnChanged();
    partial void OnAddressEnChanging(string value);
    partial void OnAddressEnChanged();
    partial void OnApartmentEnChanging(string value);
    partial void OnApartmentEnChanged();
    partial void OnRoleEnChanging(string value);
    partial void OnRoleEnChanged();
    partial void OnSubRoleEnChanging(string value);
    partial void OnSubRoleEnChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnAdminKbnChanging(int value);
    partial void OnAdminKbnChanged();
    partial void OnCREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DATEChanged();
    partial void OnUPDATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATE_DATEChanged();
    #endregion
		
		public M_ACCOUNT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seq", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int seq
		{
			get
			{
				return this._seq;
			}
			set
			{
				if ((this._seq != value))
				{
					this.OnseqChanging(value);
					this.SendPropertyChanging();
					this._seq = value;
					this.SendPropertyChanged("seq");
					this.OnseqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passwd", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Passwd
		{
			get
			{
				return this._Passwd;
			}
			set
			{
				if ((this._Passwd != value))
				{
					this.OnPasswdChanging(value);
					this.SendPropertyChanging();
					this._Passwd = value;
					this.SendPropertyChanged("Passwd");
					this.OnPasswdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this.OnLastNameChanging(value);
					this.SendPropertyChanging();
					this._LastName = value;
					this.SendPropertyChanged("LastName");
					this.OnLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this.OnFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FirstName = value;
					this.SendPropertyChanged("FirstName");
					this.OnFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pref", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Pref
		{
			get
			{
				return this._Pref;
			}
			set
			{
				if ((this._Pref != value))
				{
					this.OnPrefChanging(value);
					this.SendPropertyChanging();
					this._Pref = value;
					this.SendPropertyChanged("Pref");
					this.OnPrefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apartment", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Apartment
		{
			get
			{
				return this._Apartment;
			}
			set
			{
				if ((this._Apartment != value))
				{
					this.OnApartmentChanging(value);
					this.SendPropertyChanging();
					this._Apartment = value;
					this.SendPropertyChanged("Apartment");
					this.OnApartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubRole", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SubRole
		{
			get
			{
				return this._SubRole;
			}
			set
			{
				if ((this._SubRole != value))
				{
					this.OnSubRoleChanging(value);
					this.SendPropertyChanging();
					this._SubRole = value;
					this.SendPropertyChanged("SubRole");
					this.OnSubRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastNameEn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LastNameEn
		{
			get
			{
				return this._LastNameEn;
			}
			set
			{
				if ((this._LastNameEn != value))
				{
					this.OnLastNameEnChanging(value);
					this.SendPropertyChanging();
					this._LastNameEn = value;
					this.SendPropertyChanged("LastNameEn");
					this.OnLastNameEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstNameEn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FirstNameEn
		{
			get
			{
				return this._FirstNameEn;
			}
			set
			{
				if ((this._FirstNameEn != value))
				{
					this.OnFirstNameEnChanging(value);
					this.SendPropertyChanging();
					this._FirstNameEn = value;
					this.SendPropertyChanged("FirstNameEn");
					this.OnFirstNameEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrefEn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PrefEn
		{
			get
			{
				return this._PrefEn;
			}
			set
			{
				if ((this._PrefEn != value))
				{
					this.OnPrefEnChanging(value);
					this.SendPropertyChanging();
					this._PrefEn = value;
					this.SendPropertyChanged("PrefEn");
					this.OnPrefEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityEn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CityEn
		{
			get
			{
				return this._CityEn;
			}
			set
			{
				if ((this._CityEn != value))
				{
					this.OnCityEnChanging(value);
					this.SendPropertyChanging();
					this._CityEn = value;
					this.SendPropertyChanged("CityEn");
					this.OnCityEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressEn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AddressEn
		{
			get
			{
				return this._AddressEn;
			}
			set
			{
				if ((this._AddressEn != value))
				{
					this.OnAddressEnChanging(value);
					this.SendPropertyChanging();
					this._AddressEn = value;
					this.SendPropertyChanged("AddressEn");
					this.OnAddressEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApartmentEn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApartmentEn
		{
			get
			{
				return this._ApartmentEn;
			}
			set
			{
				if ((this._ApartmentEn != value))
				{
					this.OnApartmentEnChanging(value);
					this.SendPropertyChanging();
					this._ApartmentEn = value;
					this.SendPropertyChanged("ApartmentEn");
					this.OnApartmentEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleEn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RoleEn
		{
			get
			{
				return this._RoleEn;
			}
			set
			{
				if ((this._RoleEn != value))
				{
					this.OnRoleEnChanging(value);
					this.SendPropertyChanging();
					this._RoleEn = value;
					this.SendPropertyChanged("RoleEn");
					this.OnRoleEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubRoleEn", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SubRoleEn
		{
			get
			{
				return this._SubRoleEn;
			}
			set
			{
				if ((this._SubRoleEn != value))
				{
					this.OnSubRoleEnChanging(value);
					this.SendPropertyChanging();
					this._SubRoleEn = value;
					this.SendPropertyChanged("SubRoleEn");
					this.OnSubRoleEnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminKbn", DbType="Int NOT NULL")]
		public int AdminKbn
		{
			get
			{
				return this._AdminKbn;
			}
			set
			{
				if ((this._AdminKbn != value))
				{
					this.OnAdminKbnChanging(value);
					this.SendPropertyChanging();
					this._AdminKbn = value;
					this.SendPropertyChanged("AdminKbn");
					this.OnAdminKbnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATE_DATE
		{
			get
			{
				return this._UPDATE_DATE;
			}
			set
			{
				if ((this._UPDATE_DATE != value))
				{
					this.OnUPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_DATE = value;
					this.SendPropertyChanged("UPDATE_DATE");
					this.OnUPDATE_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.R_ORDER")]
	public partial class R_ORDER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _seq;
		
		private string _EMail;
		
		private string _Passwd;
		
		private int _Obverse;
		
		private int _Reverse;
		
		private System.Nullable<System.DateTime> _CREATE_DATE;
		
		private System.Nullable<System.DateTime> _UPDATE_DATE;
		
    #region 拡張メソッドの定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnseqChanging(int value);
    partial void OnseqChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnPasswdChanging(string value);
    partial void OnPasswdChanged();
    partial void OnObverseChanging(int value);
    partial void OnObverseChanged();
    partial void OnReverseChanging(int value);
    partial void OnReverseChanged();
    partial void OnCREATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATE_DATEChanged();
    partial void OnUPDATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnUPDATE_DATEChanged();
    #endregion
		
		public R_ORDER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_seq", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int seq
		{
			get
			{
				return this._seq;
			}
			set
			{
				if ((this._seq != value))
				{
					this.OnseqChanging(value);
					this.SendPropertyChanging();
					this._seq = value;
					this.SendPropertyChanged("seq");
					this.OnseqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passwd", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string Passwd
		{
			get
			{
				return this._Passwd;
			}
			set
			{
				if ((this._Passwd != value))
				{
					this.OnPasswdChanging(value);
					this.SendPropertyChanging();
					this._Passwd = value;
					this.SendPropertyChanged("Passwd");
					this.OnPasswdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Obverse", DbType="Int NOT NULL")]
		public int Obverse
		{
			get
			{
				return this._Obverse;
			}
			set
			{
				if ((this._Obverse != value))
				{
					this.OnObverseChanging(value);
					this.SendPropertyChanging();
					this._Obverse = value;
					this.SendPropertyChanged("Obverse");
					this.OnObverseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reverse", DbType="Int NOT NULL")]
		public int Reverse
		{
			get
			{
				return this._Reverse;
			}
			set
			{
				if ((this._Reverse != value))
				{
					this.OnReverseChanging(value);
					this.SendPropertyChanging();
					this._Reverse = value;
					this.SendPropertyChanged("Reverse");
					this.OnReverseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATE_DATE
		{
			get
			{
				return this._UPDATE_DATE;
			}
			set
			{
				if ((this._UPDATE_DATE != value))
				{
					this.OnUPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._UPDATE_DATE = value;
					this.SendPropertyChanged("UPDATE_DATE");
					this.OnUPDATE_DATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
