<?xml version="1.0" encoding="utf-8"?><Database Name="NameCard" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-8UU5POT;Initial Catalog=NameCard;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NameCardConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.M_ACCOUNT" Member="M_ACCOUNT">
    <Type Name="M_ACCOUNT">
      <Column Name="seq" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Passwd" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pref" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apartment" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubRole" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastNameEn" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstNameEn" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PrefEn" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CityEn" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AddressEn" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ApartmentEn" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoleEn" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubRoleEn" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tel" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AdminKbn" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.R_ORDER" Member="R_ORDER">
    <Type Name="R_ORDER">
      <Column Name="seq" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Passwd" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Obverse" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Reverse" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>